apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s/ -f docker-compose.hub.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: broker
  name: broker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: broker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./k8s/ -f docker-compose.hub.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: broker
    spec:
      containers:
        - env:
            - name: CONTABO_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: CONTABO_DOMAIN
                  name: envs--env-common
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_CLIENT_ID
                  name: envs--env-broker
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_CLIENT_SECRET
                  name: envs--env-broker
            - name: KEYCLOAK_HOSTNAME
              value: keycloak:8080
            - name: KEYCLOAK_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_USERNAME
                  name: envs--env-broker
            - name: LOCALHOST_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: LOCALHOST_DOMAIN
                  name: envs--env-common
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ROOT_PASSWORD
                  name: envs--env-minio
            - name: MINIO_ROOT_USER
              valueFrom:
                configMapKeyRef:
                  key: MINIO_ROOT_USER
                  name: envs--env-minio
            - name: MONGO_COLLECTION
              valueFrom:
                configMapKeyRef:
                  key: MONGO_COLLECTION
                  name: envs--env-mongo-client
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  key: MONGO_DB
                  name: envs--env-mongo-client
            - name: MONGO_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: MONGO_HOSTNAME
                  name: envs--env-mongo-client
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_DATABASE
                  name: envs--env-mongodb
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: envs--env-mongodb
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: envs--env-mongodb
            - name: MONGO_PARAMS
              valueFrom:
                configMapKeyRef:
                  key: MONGO_PARAMS
                  name: envs--env-mongo-client
            - name: MONGO_PASSWD
              valueFrom:
                configMapKeyRef:
                  key: MONGO_PASSWD
                  name: envs--env-mongo-client
            - name: MONGO_REPLICA_SET_NAME
              valueFrom:
                configMapKeyRef:
                  key: MONGO_REPLICA_SET_NAME
                  name: envs--env-mongodb
            - name: MONGO_USER
              valueFrom:
                configMapKeyRef:
                  key: MONGO_USER
                  name: envs--env-mongo-client
          image: marcotommoro/cc-broker:latest
          name: broker
          ports:
            - containerPort: 5001
          resources: {}
          volumeMounts:
            - mountPath: /app/src
              name: broker-claim0
      restartPolicy: Always
      volumes:
        - name: broker-claim0
          persistentVolumeClaim:
            claimName: broker-claim0
status: {}
