apiVersion: v1
data:
  POSTGRES_DB: keycloak
  POSTGRES_PASSWORD: password
  POSTGRES_USER: keycloak
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-keycloak-envs--env-postgres-keycloak
  name: envs--env-postgres-keycloak
