apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s/ -f docker-compose.hub.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./k8s/ -f docker-compose.hub.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: BROKER_HOSTNAME
              value: broker:5001
            - name: BROKER_HOSTNAME_EXTERNAL
              value: 127.0.0.1:5001
            - name: CONTABO_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: CONTABO_DOMAIN
                  name: envs--env-common
            - name: KEYCLOAK_HOSTNAME
              value: keycloak:8080
            - name: LOCALHOST_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: LOCALHOST_DOMAIN
                  name: envs--env-common
          image: marcotommoro/cc-frontend:latest
          name: frontend
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: frontend-claim0
      restartPolicy: Always
      volumes:
        - name: frontend-claim0
          persistentVolumeClaim:
            claimName: frontend-claim0
status: {}
