apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s/ -f docker-compose.hub.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: keycloak
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./k8s/ -f docker-compose.hub.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: keycloak
    spec:
      containers:
        - args:
            - start-dev
          env:
            - name: KC_DB
              valueFrom:
                configMapKeyRef:
                  key: KC_DB
                  name: envs--env-keycloak
            - name: KC_DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: KC_DB_PASSWORD
                  name: envs--env-keycloak
            - name: KC_DB_URL
              valueFrom:
                configMapKeyRef:
                  key: KC_DB_URL
                  name: envs--env-keycloak
            - name: KC_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: KC_DB_USERNAME
                  name: envs--env-keycloak
            - name: KEYCLOAK_ADMIN
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_ADMIN
                  name: envs--env-keycloak
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_ADMIN_PASSWORD
                  name: envs--env-keycloak
          image: quay.io/keycloak/keycloak:20.0.2
          name: keycloak
          ports:
            - containerPort: 8080
          resources: {}
      hostname: keycloak
      restartPolicy: Always
status: {}
