apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s/ -f docker-compose.hub.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: mongoclient
  name: mongoclient
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongoclient
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./k8s/ -f docker-compose.hub.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: mongoclient
    spec:
      containers:
        - image: mongoclient/mongoclient:latest
          name: mongoclient
          ports:
            - containerPort: 3000
          resources: {}
      hostname: mongoclient
      restartPolicy: Always
status: {}
